version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shapes"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ahh0f3plgk73"
s3_prefix = "shapes"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

