AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is the template to calculate area of shapes using lambda and API gateway
Globals:
  Function:
    Timeout: 20
Resources:
  ShapesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: geometry
      Handler: lambda.EntryPoint::handleRequest
      FunctionName: Shapes
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        GetShapes:
          Type: Api
          Properties:
            Path: /shapes/{shapeName}
            Method: get
Outputs:
  GetShapesApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shapes/{shapeName}?side={value}&side={value}"
  ShapesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShapesFunction.Arn